name: rise-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - rise
  - scipy
  - nibabel
  - nipype
  - pip:
    - nilearn
    - sklearn

